### PR TITLE
Improve English localization of "Duality" buffs

### PR DESCRIPTION
**Pull request by MaddestOfLads**
I really loved playing this mod, but I noticed some issues with the English localization, so I tried to improve it wherever I could.

Only "Duality" buffs are changed for now, as a test. If the mod's devs like it, I'll localize the rest of the mod too.

No code has been changed - just the English text in .json files.

Here are images listing all the changes and the reasoning behind them:

[(The images are a bit low-res which might make them hard to read, click here for the original Excel file.)](https://github.com/user-attachments/files/16642357/randombuff.xlsx)

### CODE REVIEW

**Comment by NicoWico** [comment]
hiya, i made most of these descriptions to help out, not focusing much on the flow of sentences and rather just getting them understandable and readable in english since they were pretty scuffed before.
most of these changes are good but i feel like the names should stay the same incase it messes with stuff elsewhere with buff ids and stuff (unless you didnt change that cus github is breaking and wont let me see). 

also i like how neither of us knew what to do with "mushrooms gain mobility".

**Comment by MaddestOfLads** [comment]
Oh, you worked on the original translation? Cool! Yeah, I tried to make them a bit more polished, but it definitely wouldn't have been as easy without your existing translations.

AFAIK, changing the names shouldn't mess with any code - the abilities have their own IDs in their .json files and I didn't touch those, I only changed stuff in the "English": section. I might theoretically be wrong since I didn't do any testing but I'm 99% certain that simply changing the localization data won't break anything.

**Comment by NicoWico** [comment]
Yea that should be fine then. 
also thanks for changing all the "slugcat" into "your slugcat", i was already halfway through all of the cards when i realized i should have changed it to "your slugcat" and didnt have the patience to go back through all of them at the time, i was gonna change them all later so you saved me some time lol

**Comment by NicoWico** [comment]
going through these again i have a few i dont quite like
 "omnidirectional bomb aiming" doesnt really mean anything since you can already throw bombs down just like with spears
"Bombs become harder, better, faster, and stronger!" i get its a reference but it doesnt explain it very well, plus "harder" could confuse people.
"Midas's finger" should be "Midas' touch" since thats the mythological name for the touch itself, plus "s's" is incorrect
the "bind with temperature" cards _give_ you the temperature card when picked up, hence being bound to temperature. having "Requires temperature" might make people assume they need another card for it to work.
"Your slugcat becomes incredibly annoying" should be "Your slugcat becomes annoying to talk to", having just incredibly annoying might put people off since it doesnt explain enough to show that its not going to make the game significantly more annoying to play
"ropeket launcher" could just be "rope-ket launcher" so its easier to pronounce at a glance, its mostly just hard to understand without the dash


minor nitpicks
should keep "Fancy wings" in the batfly hybrid description, it was there in the original description and i found it kinda cute lol
the name "armstron" probably isnt intentional, but its funny cus its armstrong with zero g

thats all i have to say, otherwise good changes :)

**Comment by MaddestOfLads** [comment]
Thanks for the second opinion! Always nice to have someone go through the trouble of doing some quality control.
**I'll propose some changes, tell me what you think, and after we settle on everything I'll update the fork.**

"Omnidirectional bomb aiming" -> "Reworked bomb aiming"
(It's a shame I don't know how the aiming exactly works yet so I can't be more specific, I might update that if I ever find it out)

"Bombs become harder, better, faster and stronger." -> "Bombs fly faster and further, and hit harder." Yeah, we can forego the reference, and I think "hit harder" is clear enough to intuitively read as "more damage and knockback". So it should communicate all the stats in the CN version well enough.

"MIdas's finger" -> "Midas' Touch"
You're right, I thought s's was acceptable for non-plural verbs, googling shows I was wrong. Good to know!

"Requires Temperature" -> "Precondition: Temperature" I don't know exactly how the precondition works, so yeah, let's play it safe and do what Google Translate says.

"Your slugcat becomes incredibly annoying" -> "Talking to your slugcat feels insufferable." Incorporates the "talking" like you suggested, but I mixed it up a bit for flow.

"Ropecket launcher" I... just don't like this one. Personal preference, I know, but the "k" sound after "p" feels like too much of a stretch to be a good pun. I don't know, I just think "Slingshot" gets the point across better and also rolls off the tongue more.

(Maybe something like "Rope it, launch 'er!"? Turns the pun into a mini-sentence that flows a bit better and still sounds like "rocket launcher". I still think "slingshot" fits better but maybe this works as a compromise?)

"Fancy wings" Agreed. To keep the same format for all exclamations, I'll put it in the pros.
"Your slugcat becomes a batfly hybrid! It grows fancy wings that let it fly, but becomes more fragile and dies to spore puffs."
(Should be fine to forego the "you fly by jumping" part in favor of flow, I feel like it's intuitive enough to be omitted.)

Armstron with zero G: agreed, that is a good one, I'm reverting it. (It's technically 1/6G... but to hell with it, it's a smart pun, smart puns get a pass.)

Also one unrelated change I thought of later, and want to put in:
Cluster Bomb: "Explosives split into several lesser explosives on detonation." -> "Explosions spawn lesser bombs on detonation."
Just some rephrasing to remove the redundancy.

(damn, if I end up translating the whole thing I'll become an expert on this mod despite having played it for an hour tops so far lmao)

Thoughts? Objections? Any other changes that you thought of in the meantime?

**Comment by NicoWico** [comment]
i get the issue with ropeket launcher, my suggestion was more of a possible option to keep it as the previous description but slingshot is a pretty good replacement name.
I'm doing my own testing with every card to figure out anything needed for descriptions so if something needs a change in the future i can fix it! (btw if you do want to do your own testing, you can use the mod's remix menu to unlock every card and then go into sandbox mode through free mode. there you can give yourself any cards and increase/decrease stacks for testing purposes)

Other than that, everything is pretty good and definitely improves on my descriptions lol.

**Comment by MaddestOfLads** [comment]
(...on second thought, I changed my mind. I wanna keep the pun in some way. Let's do "Rope it, launch 'er!" for the title and "Pole plants become slingshots." for the description. Keeps the pun + keeps "slingshot" + understandable + bonus points for brevity.)

Good to know about the remix menu! If you're going through the duality ones, I'll let you handle these, but I'll be sure to use it for future translations (if the devs accept my humble contribution hope hope)

**Comment by NicoWico** [comment]
im putting off the duality ones until this pull gets merged or denied lol, itll probably get merged since they are better descriptions and the devs are pretty open to english localization help

**Comment by MaddestOfLads** [comment]
yeah, I hope so

note to devs: if you do decide to merge, please wait until I push the updates

**Comment by MaddestOfLads** [comment]
(On second thought... "Midas' Touch" -> "Midas' Paws.")

**Comment by NicoWico** [comment]
Midas' Paws is amazing

**Comment by MaddestOfLads** [comment]
Alright, updates pushed, should be good to merge!

**Comment by NicoWico** [comment]
have you talked with the devs btw? they added you to the credits for localization assistance :3

**Comment by MaddestOfLads** [comment]
they have?! no, I haven't talked to them yet, the trailer video stated they can be contacted through discord but I haven't been able to find the server

**Comment by MaddestOfLads** [comment]
But I'm happy to know that!

**Comment by NicoWico** [comment]
yea! in the special thanks of the credits in buffassets has both of us now
also i got into contact with harvie by commenting on the randombuff steam page asking how to contact them and he added me on steam

**Review by HarvieSorroway — APPROVED** [review]

**Pull request merged**
